### PR TITLE
Add certificate/key/token generation 

### PR DESCRIPTION
**Pull request by mikeln**
These are the needed scripts.  
Do this PR first as it is completely separated from the rest.

### CODE REVIEW

**Comment by l337ch** [comment]
why such a complex script to create a unsecure self-signed ssl cert when all is needed is something like 
```
sudo openssl req \
-x509 \
-nodes \
-days 3650 \
-newkey rsa:2048 \
-subj "/C=US/ST=Washington/L=Seattle/O=Boss/CN=*.kubeme.io" \
-keyout /<path_to_ssl_dir>/selfie.key \
-out /<path_to_ssl_dir>/selfie.crt
```

We can then use ansible with cloudinit or just ansible alone  to run this and install it in the proper locations. Am I missing something?

**Comment by l337ch** [comment]
Can you refresh my memory as to why we need to enable tokens? We use https already and don't seem to require tokens being enabled anywhere.

**Comment by mikeln** [comment]
the make-ca-certs.sh comes directly from Google.  I wanted to make sure to reuse something that I know works instead of rolling a new one.  There are minor changes to simplify some args.

It is complicated because it generates 1) self-signed CA,  2) a CSR  3) several sets of key pairs needed to enable SSL/TLS for the master components.  

The e2e conformance tests (density is one of them) scripts assume that https://<master ip> is the entry point (not https://<master ip>:8080)  

To enable full encrypt/auth requires all the certs/keys/tokens generated.  What you see is NOT a full setup, just the minimum that was needed to get the density test running.

The e2e tests require automatic Service Account w/secret creation on Namespace creation.  This is the piece that doesn't work for our setup.   Through hasty trial and error, the Admission control needs to be fully enabled, which then requires component auth method.  The token(s) seem to be the preferred current method to accomplish this, and granted, the easiest way to do this.  NOTE: I was unable to just add admission controls and tokens to get the service creation to work.  It requires an associated secret be created, which appears to work only if the apiserver TLS key pair are specified also.

The certs/keys and tokens are created together to make it much easier to create the node kubelet/kube-proxy kubeconfig because each file includes the text version of the generated ca.crt and the correct token for that component.

**Comment by mikeln** [comment]
Incorporated in: https://github.com/Samsung-AG/kraken/pull/136

**Pull request closed without merging**
