### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by maratoid**

### CODE REVIEW

**Comment by l337ch** [comment]
i'm running this locally and getting stuck at 

```
 ./kraken local --unittest up
checking for Vagrant... yes
Executing: KRAKEN_CLUSTER='local' VAGRANT_DOTFILE_PATH='/Users/leechang/Documents/workspace/github.com/l337ch/kraken/kubernetes/local' VAGRANT_CWD='/Users/leechang/Documents/workspace/github.com/l337ch/kraken/kubernetes' KRAKEN_UNITTEST=true vagrant up
Bringing machine 'etcd' up with 'virtualbox' provider...
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-01' up with 'virtualbox' provider...
Bringing machine 'node-02' up with 'virtualbox' provider...
Bringing machine 'node-03' up with 'virtualbox' provider...
==> etcd: Importing base box 'coreos-alpha'...
==> etcd: Matching MAC address for NAT networking...
==> etcd: Checking if box 'coreos-alpha' is up to date...
==> etcd: Setting the name of the VM: kubernetes_etcd_1432217641863_10340
==> etcd: Fixed port collision for 22 => 2222. Now on port 2200.
==> etcd: Clearing any previously set network interfaces...
==> etcd: Preparing network interfaces based on configuration...
    etcd: Adapter 1: nat
    etcd: Adapter 2: hostonly
==> etcd: Forwarding ports...
    etcd: 22 => 2200 (adapter 1)
==> etcd: Running 'pre-boot' VM customizations...
==> etcd: Booting VM...
==> etcd: Waiting for machine to boot. This may take a few minutes...
    etcd: SSH address: 127.0.0.1:2200
    etcd: SSH username: core
    etcd: SSH auth method: private key
    etcd: Warning: Connection timeout. Retrying...
==> etcd: Machine booted and ready!
==> etcd: Setting hostname...
==> etcd: Configuring and enabling network interfaces...
==> etcd: Running provisioner: file...
==> etcd: Running provisioner: shell...
    etcd: Running: inline script
==> etcd: Running provisioner: serverspec...
......

Finished in 43.97 seconds (files took 25.22 seconds to load)
6 examples, 0 failures

==> etcd: Running triggers after up...
==> etcd: making sure ssh agent has the default vagrant key...
Identity added: /Users/leechang/.vagrant.d/insecure_private_key (/Users/leechang/.vagrant.d/insecure_private_key)
==> master: Importing base box 'coreos-alpha'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'coreos-alpha' is up to date...
==> master: Setting the name of the VM: kubernetes_master_1432217707036_42776
==> master: Fixed port collision for 22 => 2222. Now on port 2201.
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 => 2201 (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2201
    master: SSH username: core
    master: SSH auth method: private key
    master: Warning: Connection timeout. Retrying...
==> master: Machine booted and ready!
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: serverspec...
......FF.
```

**Comment by l337ch** [comment]
ok it completed after a long time. the tests need to run after the whole cluster starts or there are always going to be failures. did i run this incorrectly?

**Comment by maratoid** [comment]
run integration tests with 
   
    ./kraken test local
    ./kraken test aws

**Comment by l337ch** [comment]
the minions name was deprecate for nodes a few versions ago and no longer returns anything. the call should be 
```
kubectl get nodes
```

**Pull request merged**
