### PR TITLE
Adding vagrant-aws-route53 support.

### PR DESCRIPTION
**Pull request by l337ch**

### CODE REVIEW

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by l337ch** [comment]
i think all the pieces are there now but i tests is failing because it doesn't retry giving the services time to install.

**Comment by maratoid** [comment]
retest this please

**Comment by l337ch** [comment]
retest this please

**Comment by l337ch** [comment]
retest this please

**Comment by l337ch** [comment]
retest this please

**Comment by l337ch** [comment]
retest this please

**Comment by l337ch** [comment]
retest this please

**Comment by l337ch** [comment]
retest this please

**Pull request merged**
