### PR TITLE
conformance test running against arbitrary conformance branches

### PR DESCRIPTION
**Pull request by spiffxp**
Minimal set of args needed to get conformance tests to run against 4 different branches.  Could use some cleanup, but it's at a point where things run, so I'd like to get it merged in, and do cleanup in a separate PR

### CODE REVIEW

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by l337ch** [comment]
lgtm

**Pull request merged**
