### PR TITLE
Create a runable kraken local and move cert objects to using etcd vs S3

### PR DESCRIPTION
**Pull request by l337ch**

### CODE REVIEW

**Comment by l337ch** [comment]
I still need to rebase with master. I was running into inconsistent results during AWS testing. I believe I have fixed the bugs but I want to see what jenkins thinks :)

**Comment by l337ch** [comment]
please retest this

**Comment by l337ch** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by maratoid** [comment]
retest this please

**Comment by l337ch** [comment]
DO NOT MERGE. I inadvertently saved the wrong version of local.tf into this commit. I need to remove the local ansible provisioner.

**Pull request merged**
