### PR TITLE
Breaking up Vagrantfiles for easier grokking. Adding a small kraken helper tool

### PR DESCRIPTION
**Pull request by maratoid**

### CODE REVIEW

**Comment by maratoid** [comment]
per discussion with @l337ch, we'll get rid of ruby version manager specific pinnings, and just pin to ruby 2.0.0 in the Gemfile for now.

**Comment by l337ch** [comment]
does the 'v' in 'kraken v local up' serve a purpose? would it be more correct to use 'kraken local up'?

**Comment by l337ch** [comment]
kraken is replacing vagrant he so call v seems redundant?

**Comment by maratoid** [comment]
v - vagrant
k - kubectl

**Comment by l337ch** [comment]
is the user going to use kraken instead of kubectl? if that's the case we should discuss because that's antipattern to how you're supposed to use kubectl with multiple clusters.

**Comment by maratoid** [comment]
I just wanted to not type in '--kubeconfig=<path>' every time. what would be the right way to control multiple clusters?

**Comment by l337ch** [comment]
that is one way to select a cluster but you can also use kubectl config to set the cluster up. if the purpose of kraken is to provide shorcuts then we might consider adding fleetctl and etcdctl. the changes are getting large enough that we should come up with a design. bytheway did you move aws.box on purpose from docker?

**Comment by l337ch** [comment]
I'm being forced to use Ruby 2.0.0. is this by design?

**Pull request merged**
