### PR TITLE
Change deprecated filename per warning from terraform 0.6.8

### PR DESCRIPTION
**Pull request by spiffxp**
Unfortunately this is a breaking change, at least for terraform 0.6.6
users, so you'll need to upgrade per instructions in the README to
follow this

### CODE REVIEW

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
retest this please

**Comment by mikeln** [comment]
LGTM

**Pull request merged**
