### PR TITLE
Nginx proxy now with SSL support and self-signed cert creation.

### PR DESCRIPTION
**Pull request by l337ch**

### CODE REVIEW

**Comment by l337ch** [comment]
retest

**Comment by l337ch** [comment]
retest this please

**Comment by l337ch** [comment]
I ran the conformance-test against this using the HTTP endpoint. 
kubeconfig
```
apiVersion: v1
clusters:
- cluster:
    api-version: v1
    server: https://lee-master.kubeme.io
    insecure-skip-tls-verify: true
  name:
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

And results are here:
https://gist.github.com/l337ch/83153e7f7603e1b8ca51

**Comment by spiffxp** [comment]
LGTM

**Pull request merged**
