### PR TITLE
Enforce ruby at 2.2.1

### PR DESCRIPTION
**Pull request by spiffxp**

### CODE REVIEW

**Comment by l337ch** [comment]
There was a PR for this earlier and was talked about. In short. We don't want this to be as open as possible because we want this to be used by as many in the community as possible

**Comment by l337ch** [comment]
ruby 2.0+ is acceptable is it not. is there a reason to pin at 2.2.1?

**Comment by spiffxp** [comment]
I like to use bundler / rbenv / rvm to enforce and switch rubies for me, keeps things consistent between local and ci.  They don't support ranges for pinning though.  It weirded me out to see ruby version checks directly in our scripts.  I can see the pros for pinning things loosely and letting heterogeneity do its thing, but I just think it's simpler if everyone uses the exact same thing.

**Comment by l337ch** [comment]
if this was for our internal use we should be locking things down. in PR 52 marat added a check for version 2.x.x. I don't see much pinning happening on other projects. Should we remove the ruby check completely?

**Comment by spiffxp** [comment]
Well, better to declare your version dependencies somehow.  If you're opposed to this more specific enforcement, then I would leave it in that script, copy it as needed to other scripts, and I'll just use a .gitignore'd .ruby-version for now.

**Comment by l337ch** [comment]
@countspongebob should decide this as i really don't have a strong opinion either way. but i want to make sure it's easy to use by the general public.

**Comment by l337ch** [comment]
talked to bob and he feels that for testing and consistency between versions we should pin to a specific versions of ruby and gems. we can deal with any fallout later.

**Pull request merged**
